### ISSUE TITLE
sorbet-unwrap: abstracts methods may mask implementing methods

### ISSUE THREAD

**Issue by md-work** [AaronC81/pry-sorbet#3]
`sorbet-unwrap` also unwraps abstract methods.
This is a problem, because normal Ruby code wouldn't have abstract methods at all.
Usually Sorbet hides abstracts methods, so Ruby ignores this concept which it doesn't know.

@paracycle (see also https://github.com/AaronC81/pry-sorbet/pull/2 )
Do you have an Idea how to ignore methods with `mode == T::Private::Methods::Modes.abstract` when unwrapping?

Background: https://github.com/sorbet/sorbet/issues/1969
There I tried another way to enable stepping though methods with signatures. And I ran into the same problem.

Here you can see the actual problem caused by this.
If the abstract method isn't hidden by Sorbet, it will overwrite the implementing method and change the behavior of the problem. 
[→ View on sorbet.run](https://sorbet.run/#module%20FancyModule%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20abstract!%0A%0A%20%20%23sig%20%7B%20abstract.returns(Integer)%20%7D%0A%20%20def%20foo%3B%20end%0A%0A%20%20def%20inspected_foo%0A%20%20%20%20foo.inspect%0A%20%20end%0Aend%0A%0Aclass%20Parent%0A%20%20def%20foo%0A%20%20%20%2042%0A%20%20end%0Aend%0A%0Aclass%20Child%20%3C%20Parent%0A%20%20include%20FancyModule%0A%20%20def%20initialize%0A%20%20%20%20puts(inspected_foo)%0A%20%20end%0Aend%0A%0Aif%20ENV%5B'SORBET_UNWRAP'%5D%0A%20%20require%20'pry-sorbet'%0A%20%20Pry.run_command%20'sorbet-unwrap'%0Aend%0A%0AChild.new%0A%23%20ruby%20THIS_SCRIPT%20%3D%3E%2042%0A%23%20SORBET_UNWRAP%3Dtrue%20ruby%20THIS_SCRIPT%20%3D%3E%20nil)
```ruby
module FancyModule
  extend T::Sig
  extend T::Helpers
  abstract!

  #sig { abstract.returns(Integer) }
  def foo; end

  def inspected_foo
    foo.inspect
  end
end

class Parent
  def foo
    42
  end
end

class Child < Parent
  include FancyModule
  def initialize
    puts(inspected_foo)
  end
end

if ENV['SORBET_UNWRAP']
  require 'pry-sorbet'
  Pry.run_command 'sorbet-unwrap'
end

Child.new
# ruby THIS_SCRIPT => 42
# SORBET_UNWRAP=true ruby THIS_SCRIPT => nil
```

**Comment by md-work** [comment]
This should fix it.
Please review and accept if fine.
```diff
--- a/lib/pry-sorbet/commands/unwrap_command.rb
+++ b/lib/pry-sorbet/commands/unwrap_command.rb
@@ -30,7 +30,11 @@ module PrySorbet
       signatures_by_method.values.each do |signature|
         T::Configuration.without_ruby_warnings do
           T::Private::DeclState.current.without_on_method_added do
-            signature.owner.send(:define_method, signature.method_name, signature.method)
+            if signature.mode == T::Private::Methods::Modes.abstract
+              signature.owner.send(:remove_method, signature.method_name)
+            else
+              signature.owner.send(:define_method, signature.method_name, signature.method)
+            end
           end
         end
       end
```

**Comment by paracycle** [comment]
@md-work thanks for pointing this out and recommending a patch for it. the patch looks fine to me, would you like to create a PR for it?

**Comment by md-work** [comment]
> would you like to create a PR for it?

Please just use my patch without a PR.

(I'm quite busy at the moment and I would have to register an SSH key first)

**Comment by paracycle** [comment]
It seems this issue was closed when the PR mentioned above was merged.
